"""empty message

Revision ID: 5c1e58a63727
Revises: 6c1fa3d9287d
Create Date: 2020-04-04 11:51:55.696141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1e58a63727'
down_revision = '6c1fa3d9287d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_loading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loading_type', sa.String(), nullable=True),
    sa.Column('loading', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loading',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('loading_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('loading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='loading_pkey')
    )
    op.drop_table('floor_loading')
    # ### end Alembic commands ###
